apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tanzu-java-web-app
  labels:
    app.kubernetes.io/component: run
    carto.run/workload-name: tanzu-java-web-app
spec:
  template:
    metadata:
      annotations:
        conventions.apps.tanzu.vmware.com/applied-conventions: |-
          appliveview-sample/app-live-view-connector
          appliveview-sample/app-live-view-appflavours
          appliveview-sample/app-live-view-systemproperties
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        carto.run/workload-name: tanzu-java-web-app
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.flavours: spring-boot
        tanzu.app.live.view.application.name: demo
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dmanagement.endpoint.health.show-details=always -Dmanagement.endpoints.web.exposure.include=*
        image: gcr.io/kontinue/raa/tanzu-java-web-app@sha256:fedbcef344a6493ee2709955f891a2e16e8ad9e4ca93761f1b15b104a0f6a0f4
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

